### ISSUE TITLE
Add multi-line comment support

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-view-parser#14]
From: https://github.com/canjs/canjs/issues/2432

Support something like:

```
{{! {{foo}} {{bar}} }}
```

This might be tricky.  Maybe we should use:

```
{{! {{foo}} {{bar}} !}}
```

To make parsing a bit easier.

```
{{¡ {{foo}} {{bar}} !}}
```

would be my preference!

**Comment by marshallswain** [comment]
Haha, I like the Spanish flair with the ¡
