### ISSUE TITLE
possible regex issue

### ISSUE THREAD

**Issue by gKreator** [canjs/can-view-parser#34]
There seems to be a regex issue that trims off a character after certain tags in certain situations.

First mentioned by:
![image](https://cloud.githubusercontent.com/assets/1431487/22268992/36773a58-e24f-11e6-92dd-c1fc903a1aa0.png)

Caused by:
https://github.com/canjs/can-view-parser/pull/32/files

Temporary solution: 
Downgrade can-view-parser to 3.0.3

**Comment by phillipskevin** [comment]
I have a failing test for this issue on this branch: https://github.com/canjs/can-view-parser/tree/special-in-attributes.

**Comment by justinbmeyer** [comment]
On me.  I had an off by one error.  Kevin has a fix coming.
