### ISSUE TITLE
Encode uppercase letters after `on:`

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-view-parser#60]
For https://github.com/canjs/can-stache-bindings/issues/229, we need to encode uppercase letters in new event bindings (`on:someMethod="someProp"`).

**Comment by phillipskevin** [comment]
If I'm reading the [spec](https://www.w3.org/TR/2008/REC-xml-20081126/#NT-Names) correctly, I think `:` and `_` are the only "special" characters allowed as the starting character of an attribute.

So, I propose one of these for encoding spaces and indicating the next letter should be uppercase:
- `:s:` - spaces
- `:u:` - uppercase

or 

- `_s_` - spaces
- `_u_` - uppercase

cc @justinbmeyer

**Comment by andrejewski** [comment]
Or `_:u:_` and `_:s:_`, I think these are crazy enough someone looking at the plain HTML will think "I did not make that typo."

**Comment by justinbmeyer** [comment]
I favor `:` because we're already using it, and it's less likely than `_` to be in someone's property name.  Say I wanted `on:foo_4_u_` ... then what? `on:foo___5___u___`? (assuming we escape `_` to `___`.

**Comment by James0x57** [comment]
just as an alternate idea, we could potentially encode more like this:
`on:myProp="doSomething"`
becomes
`on:myprop="doSomething" original::myprop="myProp"`
makes it a little more readable imo

**Comment by phillipskevin** [comment]
Closed by https://github.com/canjs/can-view-parser/releases/tag/v3.5.0.
