### ISSUE TITLE
Warning about missing end quotes ~8

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-view-parser#7]
From https://github.com/canjs/canjs/issues/2158

Example:

```
      <my-input {value}="name"
                (value)="updateNameOnEven(%viewModel.value)/> 
```

**Comment by phillipskevin** [comment]
We found some places where this warning is being given incorrectly.

Here is one example:
![image](https://user-images.githubusercontent.com/5851984/31550955-a26d7cb4-aff8-11e7-944b-e8090e6f1c74.png)


This is happening for this code:
![image](https://user-images.githubusercontent.com/5851984/31550972-b6815c8e-aff8-11e7-846f-1334d1711075.png)
