### ISSUE TITLE
Additional edge cases for tag balancing warnings

### ISSUE THREAD

**Issue by mjstahl** [canjs/can-view-parser#75]
* `unexpected closing tag {{/getTypeProperty('alarm:activeDevices')}} expected {{/getTypeProperty}}`

* `unexpected closing tag {{/subsystem}} expected {{/}}`

* `unexpected closing tag {{/subsystem['alarm:activeDevices:SECURITY']}} expected {{/}}`

**Comment by phillipskevin** [comment]
Related: https://github.com/canjs/steal-stache/issues/45.

**Comment by imaustink** [comment]
For the first use case:
```
{{#getTypeProperty('alarm:activeDevices')}}
    <iris-segmented-radial-segment state="ready" />
{{/getTypeProperty('alarm:activeDevices')}}
```
The correct way to express this is:
```
{{#getTypeProperty('alarm:activeDevices')}}
    <iris-segmented-radial-segment state="ready" />
{{/getTypeProperty}}
```
So the wanring seems correct.

I was able to replicate the other two warnings and there does seem to be a bug so I will continue working on this today.
