### ISSUE TITLE
TextNodes should not be inserted before the <head> element or after <body>

### ISSUE THREAD

**Issue by matthewp** [canjs/can-view-parser#97]
Given HTML/stache like:

```html
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <h1>Test</h1>
  </body>
</html>
```

There should be a TextNode between the `<head>` and `<body>` elements, but there should not be one before or after.  This jsbin shows how it works in browsers: https://jsbin.com/tecinoboya/edit?html,console

**Comment by justinbmeyer** [comment]
that's weird.  I wonder if this is `can-view-parser`'s job ... probably is ...

**Comment by matthewp** [comment]
I think so, it's a parsing thing. If you do `document.documentElement.innerHTML = 'testing<head></head><body></body>'` the browser will ignore the initial text node.

But if you do `document.documentElement.insertBefore(document.createTextNode("testing"), document.documentElement.firstChild)` then there will be a TextNode inserted.

So that means that TextNodes are allowed there, they just wont be parsed by the browser when it reads the document or parses innerHTML.

**Comment by matthewp** [comment]
Also the browser will insert a head and body tag if you don't provide one. I didn't do that in this change but it's something that can-view-parser should probably do I guess...
